/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.BorderLayout;
import javax.swing.JFormattedTextField;
import javax.swing.JSplitPane;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.MaskFormatter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Đứcc
 */
public class Menu extends javax.swing.JFrame implements UndoableEditListener{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        txaNote.getDocument().addUndoableEditListener(manager);
       
    }
    public void showRoom(String code){
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
            root = new DefaultMutableTreeNode("Single room");
//            root.add(root);
            root.add(new DefaultMutableTreeNode("Hi"));
//            model.reload(root);
    }

    /**
     *
     */

    UndoManager manager = new UndoManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCheckIN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        tbAdmin = new javax.swing.JToggleButton();
        tbUndo = new javax.swing.JToggleButton();
        tbRedo = new javax.swing.JToggleButton();
        tbSetting = new javax.swing.JToggleButton();
        tbSearch = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        pnInformations = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNote = new javax.swing.JTextArea();
        lblGender = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblPlaceOfBirth = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCMND = new javax.swing.JLabel();
        lblIssuedBy = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox();
        cbYear = new javax.swing.JComboBox();
        txtPlaceOfBirth = new javax.swing.JTextField();
        lblNationality = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaAddress = new javax.swing.JTextArea();
        txfPhone = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        txfCMND = new javax.swing.JFormattedTextField();
        txtIssuedBy = new javax.swing.JTextField();
        lblWarnName = new javax.swing.JLabel();
        lblDateOfBirthWarning = new javax.swing.JLabel();
        lblPhoneWarning = new javax.swing.JLabel();
        lblIDWarning = new javax.swing.JLabel();
        txfDate = new javax.swing.JFormattedTextField();
        lblPassport = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        txfMonth = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHethong = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmDanhmuc = new javax.swing.JMenu();

        pnCheckIN.setMaximumSize(new java.awt.Dimension(300, 322));
        pnCheckIN.setPreferredSize(new java.awt.Dimension(300, 322));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnCheckINLayout = new javax.swing.GroupLayout(pnCheckIN);
        pnCheckIN.setLayout(pnCheckINLayout);
        pnCheckINLayout.setHorizontalGroup(
            pnCheckINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCheckINLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        pnCheckINLayout.setVerticalGroup(
            pnCheckINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCheckINLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Khách Sạn");

        jToolBar1.setRollover(true);

        tbAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/tải xuống.jpe"))); // NOI18N
        tbAdmin.setFocusable(false);
        tbAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbAdmin);

        tbUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/undo.png"))); // NOI18N
        tbUndo.setFocusable(false);
        tbUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUndoActionPerformed(evt);
            }
        });
        jToolBar1.add(tbUndo);

        tbRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/redo.png"))); // NOI18N
        tbRedo.setFocusable(false);
        tbRedo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbRedo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRedoActionPerformed(evt);
            }
        });
        jToolBar1.add(tbRedo);

        tbSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images (2).jpe"))); // NOI18N
        tbSetting.setFocusable(false);
        tbSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbSetting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbSetting);

        tbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/searchicon.png"))); // NOI18N
        tbSearch.setFocusable(false);
        tbSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbSearch);

        jPanel1.setPreferredSize(new java.awt.Dimension(460, 322));

        jSplitPane1.setPreferredSize(new java.awt.Dimension(459, 350));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Các loại Phòng");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Phòng đơn");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Phòng đôi");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Phòng gia đình");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hot dogs");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Phòng VIP");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("234");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setMaximumSize(new java.awt.Dimension(150, 64));
        jTree1.setMinimumSize(new java.awt.Dimension(50, 0));
        jTree1.setPreferredSize(new java.awt.Dimension(150, 64));
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        pnInformations.setBackground(new java.awt.Color(255, 255, 255));
        pnInformations.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quản lý thông tin"));
        pnInformations.setToolTipText("");
        pnInformations.setMaximumSize(new java.awt.Dimension(300, 322));
        pnInformations.setMinimumSize(new java.awt.Dimension(200, 0));
        pnInformations.setPreferredSize(new java.awt.Dimension(300, 322));

        lblName.setText("Họ và Tên");

        txaNote.setColumns(20);
        txaNote.setRows(5);
        jScrollPane2.setViewportView(txaNote);

        lblGender.setText("Giới Tính");

        lblDateOfBirth.setText("Ngày Sình");

        lblPlaceOfBirth.setText("Nơi Sinh");

        lblAddress.setText("Địa chỉ");

        lblPNumber.setText("Điện Thoại");

        lblEmail.setText("E-mail");

        lblCMND.setText("Số CMND");

        lblIssuedBy.setText("Nơi Cấp");

        lblNote.setText("Ghi Chú");

        txtName.setMaximumSize(new java.awt.Dimension(6, 20));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        cbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", " " }));

        txtPlaceOfBirth.setMaximumSize(new java.awt.Dimension(6, 20));

        lblNationality.setText("Quốc Tịch");

        txaAddress.setColumns(20);
        txaAddress.setRows(5);
        jScrollPane3.setViewportView(txaAddress);

        try{
            txfPhone = new JFormattedTextField(new MaskFormatter("###########"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }

        try{
            txfCMND = new JFormattedTextField(new MaskFormatter("#########"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }

        lblWarnName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWarnName.setMaximumSize(new java.awt.Dimension(170, 20));
        lblWarnName.setMinimumSize(new java.awt.Dimension(170, 20));
        lblWarnName.setPreferredSize(new java.awt.Dimension(170, 20));

        lblDateOfBirthWarning.setMaximumSize(new java.awt.Dimension(170, 20));
        lblDateOfBirthWarning.setMinimumSize(new java.awt.Dimension(170, 20));
        lblDateOfBirthWarning.setPreferredSize(new java.awt.Dimension(170, 20));

        lblPhoneWarning.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhoneWarning.setMaximumSize(new java.awt.Dimension(170, 20));
        lblPhoneWarning.setMinimumSize(new java.awt.Dimension(170, 20));
        lblPhoneWarning.setPreferredSize(new java.awt.Dimension(170, 20));

        lblIDWarning.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIDWarning.setMaximumSize(new java.awt.Dimension(170, 20));
        lblIDWarning.setMinimumSize(new java.awt.Dimension(170, 20));
        lblIDWarning.setPreferredSize(new java.awt.Dimension(170, 20));

        try{
            txfDate = new JFormattedTextField(new MaskFormatter("##"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }

        lblPassport.setText("hoặc Passport");

        lblDay.setText("DD");

        lblMonth.setText("MM");

        try{
            txfMonth = new JFormattedTextField(new MaskFormatter("##"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout pnInformationsLayout = new javax.swing.GroupLayout(pnInformations);
        pnInformations.setLayout(pnInformationsLayout);
        pnInformationsLayout.setHorizontalGroup(
            pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformationsLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnInformationsLayout.createSequentialGroup()
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(lblPNumber)
                            .addComponent(lblEmail)
                            .addComponent(lblCMND)
                            .addComponent(lblIssuedBy)
                            .addComponent(lblNote))
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnInformationsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(pnInformationsLayout.createSequentialGroup()
                                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnInformationsLayout.createSequentialGroup()
                                                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txfCMND, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblPassport)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnInformationsLayout.createSequentialGroup()
                                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnInformationsLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnInformationsLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInformationsLayout.createSequentialGroup()
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateOfBirth)
                            .addComponent(lblPlaceOfBirth))
                        .addGap(18, 18, 18)
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlaceOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnInformationsLayout.createSequentialGroup()
                                .addComponent(txfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDay)
                                .addGap(27, 27, 27)
                                .addComponent(txfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInformationsLayout.createSequentialGroup()
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblGender))
                        .addGap(18, 18, 18)
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnInformationsLayout.createSequentialGroup()
                                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNationality)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblWarnName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(lblDateOfBirthWarning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnInformationsLayout.setVerticalGroup(
            pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarnName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnInformationsLayout.createSequentialGroup()
                        .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(lblNationality)
                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDateOfBirthWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateOfBirth)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDay)
                        .addComponent(lblMonth)
                        .addComponent(txfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaceOfBirth)
                    .addComponent(txtPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPNumber)
                    .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCMND)
                    .addComponent(txfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassport))
                .addGap(11, 11, 11)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIssuedBy)
                    .addComponent(txtIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNote)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        jSplitPane1.setRightComponent(pnInformations);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("OK");

        jmHethong.setText("Hệ Thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Undo");
        jmHethong.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Redo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmHethong.add(jMenuItem2);

        jMenuBar1.add(jmHethong);

        jmDanhmuc.setText("Danh Mục");
        jMenuBar1.add(jmDanhmuc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUndoActionPerformed

        if(manager.canUndo()){
        manager.undo();
        }
    }//GEN-LAST:event_tbUndoActionPerformed

    private void tbRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRedoActionPerformed
        if(manager.canRedo()){
            manager.redo();
        }
//        tbUndo.setText(manager.getUndoPresentationName());
//        tbRedo.setText(manager.getRedoPresentationName());
//        tbUndo.setEnabled(manager.canUndo());
//        tbRedo.setEnabled(manager.canRedo());
    }//GEN-LAST:event_tbRedoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbYear;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu jmDanhmuc;
    private javax.swing.JMenu jmHethong;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCMND;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDateOfBirthWarning;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIDWarning;
    private javax.swing.JLabel lblIssuedBy;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPNumber;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblPhoneWarning;
    private javax.swing.JLabel lblPlaceOfBirth;
    private javax.swing.JLabel lblWarnName;
    private javax.swing.JPanel pnCheckIN;
    private javax.swing.JPanel pnInformations;
    private javax.swing.JToggleButton tbAdmin;
    private javax.swing.JToggleButton tbRedo;
    private javax.swing.JToggleButton tbSearch;
    private javax.swing.JToggleButton tbSetting;
    private javax.swing.JToggleButton tbUndo;
    private javax.swing.JTextArea txaAddress;
    private javax.swing.JTextArea txaNote;
    private javax.swing.JFormattedTextField txfCMND;
    private javax.swing.JFormattedTextField txfDate;
    private javax.swing.JFormattedTextField txfMonth;
    private javax.swing.JFormattedTextField txfPhone;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIssuedBy;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPlaceOfBirth;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void undoableEditHappened(UndoableEditEvent e) {
//        manager.addEdit(e.getEdit());
//    }

    @Override
    public void undoableEditHappened(UndoableEditEvent e) {
        manager.addEdit(e.getEdit());
    }
}
